#!/bin/bash
cd ${0%/*} || exit 1
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allclean

runApplication blockMesh
runApplication extrudeMesh
runApplication sonicFoam
runApplication foamLog log.sonicFoam


